import type { AplicacaoFinanceira } from "@/shared/types/financeiro"

export const dadosIniciais: AplicacaoFinanceira = {
  usuario: {
    nome: "Edson Silva",
    email: "edson@kofre.app",
    avatar: "",
    moeda: "BRL",
    fusoHorario: "America/Sao_Paulo",
  },
  contas: [
    {
      id: "conta-1",
      nome: "Conta Principal",
      tipo: "corrente",
      instituicao: "Nubank",
      saldoAtual: 12840.35,
      variacaoMensal: 8.4,
    },
    {
      id: "conta-2",
      nome: "Reserva de Emergencia",
      tipo: "poupanca",
      instituicao: "Inter",
      saldoAtual: 21500,
      variacaoMensal: 2.1,
    },
    {
      id: "conta-3",
      nome: "Corretora",
      tipo: "investimento",
      instituicao: "XP",
      saldoAtual: 18320.9,
      variacaoMensal: 4.7,
    },
  ],
  cartoes: [
    {
      id: "cartao-1",
      nome: "Cartao Black",
      bandeira: "Mastercard",
      limite: 18000,
      faturaAtual: 4360.52,
      vencimento: "2026-05-08",
    },
    {
      id: "cartao-2",
      nome: "Cartao Viagens",
      bandeira: "Visa",
      limite: 7000,
      faturaAtual: 1284.2,
      vencimento: "2026-05-15",
    },
  ],
  transacoes: [
    {
      id: "trans-1",
      descricao: "Mercado Avenida",
      categoria: "Alimentacao",
      subcategoria: "Supermercado",
      valor: 428.9,
      tipo: "despesa",
      conta: "Conta Principal",
      tag: "casa",
      data: "2026-04-24",
      recorrente: false,
      contaId: "conta-1",
      contaTipo: "corrente",
      contaInstituicao: "Nubank",
    },
    {
      id: "trans-2",
      descricao: "Salario Abril",
      categoria: "Renda",
      subcategoria: "Salario",
      valor: 9500,
      tipo: "receita",
      conta: "Conta Principal",
      tag: "fixa",
      data: "2026-04-05",
      recorrente: true,
      contaId: "conta-1",
      contaTipo: "corrente",
      contaInstituicao: "Nubank",
    },
    {
      id: "trans-3",
      descricao: "Uber",
      categoria: "Transporte",
      subcategoria: "Mobilidade",
      valor: 62.3,
      tipo: "despesa",
      conta: "Conta Principal",
      tag: "trabalho",
      data: "2026-04-25",
      recorrente: false,
      contaId: "conta-1",
      contaTipo: "corrente",
      contaInstituicao: "Nubank",
    },
    {
      id: "trans-4",
      descricao: "Reserva para viagem",
      categoria: "Transferencias",
      subcategoria: "Interna",
      valor: 1200,
      tipo: "transferencia",
      conta: "Reserva de Emergencia",
      tag: "meta",
      data: "2026-04-18",
      recorrente: true,
      contaId: "conta-2",
      contaTipo: "poupanca",
      contaInstituicao: "Inter",
    },
    {
      id: "trans-5",
      descricao: "Restaurante Cais",
      categoria: "Alimentacao",
      subcategoria: "Restaurante",
      valor: 134.8,
      tipo: "despesa",
      conta: "Cartao Black",
      tag: "lazer",
      data: "2026-04-23",
      recorrente: false,
      contaTipo: "cartao_credito",
      contaInstituicao: "Mastercard",
    },
  ],
  orcamentos: [
    {
      id: "orc-1",
      categoria: "Alimentacao",
      planejado: 1800,
      realizado: 1460,
      alerta: 80,
    },
    {
      id: "orc-2",
      categoria: "Transporte",
      planejado: 900,
      realizado: 740,
      alerta: 80,
    },
    {
      id: "orc-3",
      categoria: "Lazer",
      planejado: 1200,
      realizado: 1228,
      alerta: 100,
    },
  ],
  metas: [
    {
      id: "meta-1",
      nome: "Viagem para o Chile",
      valorAlvo: 15000,
      valorAtual: 9400,
      prazo: "2026-11-30",
      contribuicaoMensal: 1200,
      conta: "Reserva de Emergencia",
      status: "no-prazo",
    },
    {
      id: "meta-2",
      nome: "Fundo de emergencia",
      valorAlvo: 30000,
      valorAtual: 21500,
      prazo: "2027-03-31",
      contribuicaoMensal: 1500,
      conta: "Reserva de Emergencia",
      status: "atencao",
    },
  ],
  insights: [
    {
      titulo: "Transporte acima da media",
      descricao: "Voce gastou 23% mais com transporte nesta semana.",
      impacto: "alerta",
    },
    {
      titulo: "Espaco no budget de alimentacao",
      descricao: "Ainda restam R$ 340 para alimentacao neste mes.",
      impacto: "oportunidade",
    },
    {
      titulo: "Oportunidade de economia",
      descricao: "Concentrar assinaturas em um unico cartao reduz risco de atraso.",
      impacto: "economia",
    },
  ],
  saude: {
    pontuacao: 82,
    nivel: "boa",
    resumo: "Seu fluxo do mes esta saudavel, com boa margem entre receita e despesa.",
  },
  serieMensal: [
    { mes: "Mai", saldo: 21200, receitas: 10400, despesas: 7200 },
    { mes: "Jun", saldo: 22600, receitas: 10900, despesas: 7400 },
    { mes: "Jul", saldo: 23800, receitas: 10800, despesas: 7600 },
    { mes: "Ago", saldo: 25100, receitas: 11100, despesas: 7900 },
    { mes: "Set", saldo: 26850, receitas: 11500, despesas: 8000 },
    { mes: "Out", saldo: 27900, receitas: 11300, despesas: 8200 },
    { mes: "Nov", saldo: 29120, receitas: 11600, despesas: 8600 },
    { mes: "Dez", saldo: 30480, receitas: 12000, despesas: 8840 },
    { mes: "Jan", saldo: 31810, receitas: 12200, despesas: 9070 },
    { mes: "Fev", saldo: 33690, receitas: 12400, despesas: 8810 },
    { mes: "Mar", saldo: 35120, receitas: 12600, despesas: 9120 },
    { mes: "Abr", saldo: 52661.25, receitas: 15420, despesas: 8934 },
  ],
  gastosPorCategoria: [
    { categoria: "Moradia", valor: 3100, percentual: 35 },
    { categoria: "Alimentacao", valor: 1460, percentual: 17 },
    { categoria: "Transporte", valor: 740, percentual: 8 },
    { categoria: "Lazer", valor: 1228, percentual: 14 },
    { categoria: "Saude", valor: 580, percentual: 6 },
    { categoria: "Outros", valor: 1826, percentual: 20 },
  ],
}
